//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LoterejaEntities : DbContext
    {
        public LoterejaEntities()
            : base("name=LoterejaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<setting> settings { get; set; }
        public virtual DbSet<drawing> drawings { get; set; }
        public virtual DbSet<winner> winners { get; set; }
        public virtual DbSet<article> articles { get; set; }
        public virtual DbSet<option> options { get; set; }
    
        public virtual ObjectResult<create_draw_Result> create_draw(Nullable<int> default_JackPot, Nullable<int> stepJackPot)
        {
            var default_JackPotParameter = default_JackPot.HasValue ?
                new ObjectParameter("default_JackPot", default_JackPot) :
                new ObjectParameter("default_JackPot", typeof(int));
    
            var stepJackPotParameter = stepJackPot.HasValue ?
                new ObjectParameter("stepJackPot", stepJackPot) :
                new ObjectParameter("stepJackPot", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<create_draw_Result>("create_draw", default_JackPotParameter, stepJackPotParameter);
        }
    
        public virtual ObjectResult<get_history_Result> get_history()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_history_Result>("get_history");
        }
    }
}
