//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class drawing
    {
        public int id_draw { get; set; }
        public string result { get; set; }
        public Nullable<int> count_winner { get; set; }
        public int JackPot { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<int> count_player { get; set; }
    }
}
