//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class option
    {
        public int id_option { get; set; }
        public string option_group { get; set; }
        public string option_key { get; set; }
        public string value { get; set; }
        public Nullable<byte> field_type { get; set; }
        public string option_name { get; set; }
    }
}
