//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class setting
    {
        public int id_settings { get; set; }
        public int timeBeforeDraw { get; set; }
        public int timeDraw { get; set; }
        public int timeAfterDraw { get; set; }
        public int minValue { get; set; }
        public int maxValue { get; set; }
        public int minJackPot { get; set; }
        public int stepJackPot { get; set; }
        public int countValue { get; set; }
        public System.DateTime date { get; set; }
    }
}
