//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class winner
    {
        public int id_winner { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string elements { get; set; }
        public string ip { get; set; }
        public System.DateTime date { get; set; }
    }
}
